### ISSUE TITLE
Capacity to initialize ice and snow cover

### ISSUE THREAD

**Issue by rqthomas** [AquaticEcoDynamics/GLM#19]
For data assimilation in lakes that freeze, the ability to specify initial ice cover is required.  Is this feature planned or has it been attempted in the past but issues were discovered?  Is there any reason to think that this isn't as simple as adding the snow, white ice, and blue ice dz variables to the glm.nml, updating code glm_init.c function with the new inputs, and having that code also trigger the ice variable to equal TRUE?

**Comment by matthipsey** [comment]
This would work - we used to have an issue where ice started on first day due to a cooling issue on day 1, though in this case it started with no ice and created ice in glm_surface on th first step.
But I am sure your proposed steps would work, there may be just an ordering issue.
If you want to give it a shot, we could sync in for v3.1

**Comment by rqthomas** [comment]
I am happy to make the changes.  Since it involves adding to the glm.nml I wanted to get feedback before proceeding.  

First, I can call the three new variables in the glm.nml: snow_height, white_ice_height, and blue_ice_height.

Second, I can place them in the init_profiles section of the glm.nml (or is the snowice section better?).  I lean to the init_profiles because it is part of initializing the physical state of the system rather than a parameter.  

How do these sound?

**Comment by rqthomas** [comment]
To restart the ice for data assimilation, the variable AvgSurfTemp also needs to be added to glm.nml and to the output.nc file  I have written code to do this and will add to the latest commit.
